export {default as Header} from './Header'
export {default as Hero} from './Hero'
export {default as Features} from './Features'
export {default as Pricing} from './Pricing'
export {default as Faq} from './Faq'
export {default as Testimonials} from './Testimonials.jsx'
export {default as Download} from './Download.jsx'
export {default as Footer} from './Footer.jsx'